### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by lfkeitel** [nitrogen-lang/nitrogen#1]
This is simply a brain dump of things I would like to see in Nitrogen. Some will be trivial to implement others will take more time and thought. They are in no specific order.

## Functions
- [ ] Implement printf and sprintf.

## Language
- [ ] Write a formal grammar
- [ ] Implicitly convert between ints to float for division. Other arithmetic operations will convert to float if even one operand is float, or remain int otherwise.

### Modules
- [ ] Files
  - ReadLine

## Interpreter
- [ ] Only die if truly unrecoverable error
- [ ] Better error messaging (parser enters panic mode)
